### ISSUE TITLE
How do I make this and jscroll.js play nicely together?

### ISSUE THREAD

**Issue by TheSqrtMinus1** [SimulatedGREG/Kappa.js#4]
My problem is that kappa.js keeps replacing emote words (Kappa, BORT, etc.) everywhere, not just inside of the selector div. It's replacing them in links, which I don't want.

And because jscroll.js uses links to autoload the next page, this is really screwing up my website.

Help, I guess.

**Comment by SimulatedGREG** [comment]
Do you by chance have a repo of this website so I can take a closer look? I believe I see the issue at first glance, but won't get a chance to test until further tonight.

**Comment by TheSqrtMinus1** [comment]
it's at https://thesqrtminus1.com/mirrors/TPPlogsGIT

**Comment by TheSqrtMinus1** [comment]
Will you push this to master?

Also, as for jscroll requesting an entire new page, I think that's a bug with jscroll and .contentSelector not functioning correctly.

**Comment by SimulatedGREG** [comment]
I believe the .contentSelector only determines which part of the DOM you want to push to the client, and doesn't control what to load, since you can't load only part of a HTTP request. But I still believe it has to grab all the assets in the long run. And yes, getting ready to push shortly.
