### ISSUE TITLE
jQuery not defined?

### ISSUE THREAD

**Issue by DigitalData** [SimulatedGREG/Kappa.js#9]
I get this error when I try to use it...

`Uncaught ReferenceError: jQuery is not defined
    at kappa.js:117`

**Comment by EmilSayahi** [comment]
Have you included jQuery in your webpage?

**Comment by DigitalData** [comment]
I did include JQ. 

Just for context, I'm making an electron app which one of the features is to provide a dashboard of messages sent to your Twitch channel. 

It doesn't matter anyway as I found a different method of parsing emoji.
